#!/usr/bin/env zsh
# z1host: the stock z1 prompt with the short hostname in front.

function prompt_z1host_setup {
  autoload -Uz prompt_z1_setup
  prompt_z1_setup "$@"

  PROMPT='%B%F{${_prompt_z1_colors[magenta]}}%m%f%b '"$PROMPT"
  _prompt_z1_full=$PROMPT
}

prompt_z1host_setup "$@"
